# Copyright (c) 2020 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
- name: Create new-ca.sh file
  copy:
    src: files/usr/local/bin/new-ca.sh
    dest: /usr/local/bin/new-ca.sh
    owner: root
    group: root
    mode: "0755"

- name: Create new-cert.sh file
  copy:
    src: files/usr/local/bin/new-cert.sh
    dest: /usr/local/bin/new-cert.sh
    owner: root
    group: root
    mode: "0755"
