# Copyright (c) 2020 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
- name: Find existing repo files
  find:
    depth: 1
    paths: /etc/yum.repos.d
    patterns: '*.repo'
  register: repo_files
  when: disable_public_repos|bool

- name: Disable repos
  command: "mv {{ item.path }} {{ item.path }}.disabled"
  loop: "{{ repo_files.files }}"
  when: disable_public_repos|bool

- name: Install extra repos
  copy:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/{{ item | basename }}"
  loop: "{{ extra_repos.split() }}"
  when: extra_repos != ""
