# Copyright (c) 2020 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
- name: Install cloud-init packages
  command: tdnf install -y cloud-init cloud-utils python3-netifaces

- name: Download cloud-init datasource for VMware Guestinfo
  get_url:
    url:  '{{ guestinfo_datasource_url }}'
    dest: /tmp/cloud-init-vmware.sh

- name: Execute cloud-init-vmware.sh
  shell: bash -o errexit -o pipefail /tmp/cloud-init-vmware.sh
  environment:
    REPO_SLUG: '{{ guestinfo_datasource_slug }}'
    GIT_REF:   '{{ guestinfo_datasource_ref }}'

- name: Remove cloud-init-vmware.sh
  file:
    path:  /tmp/cloud-init-vmware.sh
    state: absent

- name: Remove cloud-init /etc/cloud/cloud.cfg.d/99-disable-networking-config.cfg
  file:
    path: /etc/cloud/cloud.cfg.d/99-disable-networking-config.cfg
    state: absent
  when: ansible_os_family == "VMware Photon OS"
