# Copyright 2020 HAProxy Technologies
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Install DataPlane API
  get_url:
    url: '{{ dataplane_api_url }}'
    dest: /usr/local/bin/dataplaneapi
    mode: "0755"

- name: Download HAProxy 2.2.2
  get_url:
    url: '{{ haproxy_rpm_url }}'
    dest: /root/haproxy-2.2.2.rpm
  when: haproxy_rpm_url != ''

- name: Install HAProxy 2.2.2
  command: sh -c 'rpm --upgrade -vh /root/haproxy-2.2.2.rpm || true'
  when: haproxy_rpm_url != ''

- name: Create HAProxy service drop-in directory
  file:
    path: /etc/systemd/system/haproxy.service.d
    state: directory

- name: Create HAProxy cloud-init drop-in file
  copy:
    src: files/etc/systemd/system/haproxy.service.d/cloud-init.conf
    dest: /etc/systemd/system/haproxy.service.d/cloud-init.conf
    owner: root
    group: root
    mode: "0644"

- name: Create HAProxy slice drop-in file
  copy:
    src: files/etc/systemd/system/haproxy.service.d/slice.conf
    dest: /etc/systemd/system/haproxy.service.d/slice.conf
    owner: root
    group: root
    mode: "0644"

- name: Create Dataplane API systemd file
  copy:
    src: files/etc/systemd/system/dataplaneapi.service
    dest: /etc/systemd/system/dataplaneapi.service
    owner: root
    group: root
    mode: "0644"

- name: Create Dataplane API systemd slice file
  copy:
    src: files/etc/systemd/system/dataplaneapi.slice
    dest: /etc/systemd/system/dataplaneapi.slice
    owner: root
    group: root
    mode: "0644"

- name: Create Data Plane API configuration file
  copy:
    src: files/etc/haproxy/dataplaneapi.cfg
    dest: /etc/haproxy/dataplaneapi.cfg
    owner: root
    group: root
    mode: "0644"

- name: Create HAProxy configuration file
  copy:
    src: files/etc/haproxy/haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: "0644"

- name: Remove default user and the Data Plane API program from HAProxy config file
  replace:
    path: /etc/haproxy/haproxy.cfg
    after: 'userlist controller'
    regexp: '^(.+)$'
    replace: '\n'

- name: Update HAProxy log level
  replace:
    path: /etc/haproxy/haproxy.cfg
    regexp: 'log stdout format raw local0 debug'
    replace: 'log stdout format raw local0 info'

- name: Enable HAProxy service
  systemd:
    name: haproxy
    enabled: yes
    daemon_reload: yes

- name: Enable Dataplane API service
  systemd:
    name: dataplaneapi
    enabled: yes
    daemon_reload: yes
