# Copyright (c) 2020 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
- name: Install DataPlane API
  get_url:
    url: '{{ dataplane_api_url }}'
    dest: /usr/local/bin/dataplaneapi
    mode: "0755"

- name: Install HAProxy
  command: "rpm -ivh {{ haproxy_rpm_url }}"
  args:
    warn: no

- name: Enable HAProxy service
  service:
    name: haproxy
    enabled: yes

- name: Create HAProxy service drop-in directory
  file:
    path: /etc/systemd/system/haproxy.service.d
    state: directory

- name: Create HAProxy cloud-init drop-in file
  copy:
    src: files/etc/systemd/system/haproxy.service.d/cloud-init.conf
    dest: /etc/systemd/system/haproxy.service.d/cloud-init.conf
    owner: root
    group: root
    mode: "0644"

- name: Create HAProxy configuration file
  copy:
    src: files/etc/haproxy/haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: "0644"

- name: Update DataPlane API reload command
  replace:
    path: /etc/haproxy/haproxy.cfg
    regexp: 'killall -SIGUSR2 haproxy'
    replace: '/usr/bin/systemctl reload haproxy'
