# Copyright (c) 2020 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
- hosts: all
  become: yes
  roles:
  - role: common
  - role: cloudinit
  - role: haproxy
  - role: vmware
  - role: pki
  - role: sysprep
